name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: macos-11.0
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 10
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
